### ISSUE TITLE
11. Backend to Softala -service. (HIGH)

### ISSUE THREAD

**Issue by Textiili** [Ryhma-RED-Ohjelmistoprojekti-2/s24RyhmaREDbackend#3]
Backend

Deploy backend to Pouta -service. It requires account for softala.haaga-helia.fi.

Plus, edit all old Rahti codes from backend. NO RAHTI!

Update: Jukka Juslin recommends to deploy backend to softala.haaga-helia.fi via Git Bash or Putty, since softala.haaga-helia.fi is already in Pouta service. Hence, you don't have to login into Pouta -webservice. However, you do need softala.haaga-helia.fi account and password.

**Comment by KajFromHH** [comment]
Almost done. Need to running redweather.service with the new java jar of backend.
